server:
  port: 8082

spring:
  application:
    name: oenexa-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
