apiVersion: v1
kind: ConfigMap
metadata:
  name: oenexa-common-config
  namespace: oenexa-dev
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:mysql://oenexa-mysql:3306"
  SPRING_DATASOURCE_USERNAME: "oenexa"
  SPRING_REDIS_HOST: "oenexa-redis"
  SPRING_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "oenexa-kafka:9092"
  ELASTICSEARCH_HOST: "oenexa-elasticsearch"
  ELASTICSEARCH_PORT: "9200"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
